services:
  - type: web
    name: universidad
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python Universidad/manage.py collectstatic --no-input && python Universidad/manage.py migrate
    startCommand: gunicorn wsgi
